### ISSUE TITLE
Line 90 of core/udl.lua causing permagag to break

### ISSUE THREAD

**Issue by ghost** [TheFreezebug/Mercury#1]
Line 90 of lua/mercury/core/udl.lua resets ply._MercuryUserData to a new table, removing permagag data before the PostUserDataLoaded hook that handles permagags is called through modhook

Fixed by changing the line to `P._MercuryUserData.LastKnownName = P:Nick()`, I assume this would retain the intended functionality

**Comment by TheFreezebug** [comment]
Patched with live version
