### ISSUE TITLE
dev_version

### ISSUE THREAD

**Issue by ghost** [TheFreezebug/Mercury#2]
Is dev_version branch using for testing or contains old version of addon?

**Comment by TheFreezebug** [comment]
To be honest, i haven't updated the repo's in forever. I'd have to strip mercury of all of the garbage it has currently to re-commit, but i'm working on Mercury 3 which is a complete re-write.

If you want, i can commit a branch for the current version?

**Comment by TSleepingCat** [comment]
Yes, please.

**Comment by ghost** [comment]
No, thanks. I waiting Mercury 3.
